#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + '/commands/command.rb')
Dir[File.dirname(__FILE__) + '/commands/*.rb'].each {|file| require file }
require 'optparse'

options = {}


command = Commands.the_appropriate_command

puts command

0
