#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + '/commands/commands.rb')
Dir[File.dirname(__FILE__) + '/commands/*.rb'].each {|file| require file }
require 'optparse'

class OptionParser
  attr_accessor :options
end

command = Commands.the_appropriate_command

command.execute

0
